/**
 * Do not edit directly, this file was auto-generated.
 */

export const SPACING_SPACE_2PX = "2px";
export const SPACING_SPACE_4PX = "4px";
export const SPACING_SPACE_8PX = "8px";
export const SPACING_SPACE_12PX = "12px";
export const SPACING_SPACE_16PX = "16px";
export const SPACING_SPACE_20PX = "20px";
export const SPACING_SPACE_24PX = "24px";
export const SPACING_SPACE_28PX = "28px";
export const SPACING_SPACE_32PX = "32px";
export const SPACING_SPACE_40PX = "40px";
export const SPACING_SPACE_48PX = "48px";
export const SPACING_SPACE_64PX = "64px";
export const SPACING_SPACE_80PX = "0px";
export const COLORS_MAGENTA900 = "#50003F";
export const COLORS_MAGENTA800 = "#891869";
export const COLORS_MAGENTA700 = "#A91A90";
export const COLORS_MAGENTA600 = "#CA26A5";
export const COLORS_MAGENTA500 = "#E142BC";
export const COLORS_MAGENTA400 = "#F877D2";
export const COLORS_MAGENTA300 = "#FFACE5";
export const COLORS_MAGENTA200 = "#FFCEF2";
export const COLORS_MAGENTA100 = "#FEDFF3";
export const COLORS_MAGENTA50 = "#FEEFF9";
export const COLORS_PURPLE900 = "#3A1659";
export const COLORS_PURPLE800 = "#633495";
export const COLORS_PURPLE700 = "#7C3EC3";
export const COLORS_PURPLE600 = "#944DE7";
export const COLORS_PURPLE500 = "#A964F7";
export const COLORS_PURPLE400 = "#C490F9";
export const COLORS_PURPLE300 = "#DDB9FF";
export const COLORS_PURPLE200 = "#EBD5FF";
export const COLORS_PURPLE100 = "#F2E3FF";
export const COLORS_PURPLE50 = "#F9F1FF";
export const COLORS_BLUE900 = "#022255";
export const COLORS_BLUE800 = "#123E92";
export const COLORS_BLUE700 = "#1153C0";
export const COLORS_BLUE600 = "#266EF1";
export const COLORS_BLUE500 = "#068BEE";
export const COLORS_BLUE400 = "#6DAAFB";
export const COLORS_BLUE300 = "#A9C9FF";
export const COLORS_BLUE200 = "#CDDEFF";
export const COLORS_BLUE100 = "#DEE9FE";
export const COLORS_BLUE50 = "#EFF4FE";
export const COLORS_TEAL900 = "#002D33";
export const COLORS_TEAL800 = "#1A535A";
export const COLORS_TEAL700 = "#016974";
export const COLORS_TEAL600 = "#007F8C";
export const COLORS_TEAL500 = "#0095A4";
export const COLORS_TEAL400 = "#01B8CA";
export const COLORS_TEAL300 = "#77D5E3";
export const COLORS_TEAL200 = "#B0E7EF";
export const COLORS_TEAL100 = "#CDEEF3";
export const COLORS_TEAL50 = "#E2F8FB";
export const COLORS_GREEN900 = "#002F14";
export const COLORS_GREEN800 = "#0D572D";
export const COLORS_GREEN700 = "#166C3B";
export const COLORS_GREEN600 = "#0E8345";
export const COLORS_GREEN500 = "#009A51";
export const COLORS_GREEN400 = "#06C167";
export const COLORS_GREEN300 = "#7FD99A";
export const COLORS_GREEN200 = "#B1EAC2";
export const COLORS_GREEN100 = "#D3EFDA";
export const COLORS_GREEN50 = "#EAF6ED";
export const COLORS_LIME900 = "#1B2D00";
export const COLORS_LIME800 = "#365310";
export const COLORS_LIME700 = "#3F6900";
export const COLORS_LIME600 = "#4F7F06";
export const COLORS_LIME500 = "#5B9500";
export const COLORS_LIME400 = "#77B71C";
export const COLORS_LIME300 = "#A6D467";
export const COLORS_LIME200 = "#CAE6A0";
export const COLORS_LIME100 = "#DEEEC6";
export const COLORS_LIME50 = "#EEF6E3";
export const COLORS_YELLOW900 = "#392300";
export const COLORS_YELLOW800 = "#6B4100";
export const COLORS_YELLOW700 = "#845201";
export const COLORS_YELLOW600 = "#9F6402";
export const COLORS_YELLOW500 = "#B97502";
export const COLORS_YELLOW400 = "#D79900";
export const COLORS_YELLOW300 = "#F6BC2F";
export const COLORS_YELLOW200 = "#FFD688";
export const COLORS_YELLOW100 = "#FBE5B6";
export const COLORS_YELLOW50 = "#FDF2DC";
export const COLORS_AMBER900 = "#3E2000";
export const COLORS_AMBER800 = "#6B4100";
export const COLORS_AMBER700 = "#904A07";
export const COLORS_AMBER600 = "#A95F03";
export const COLORS_AMBER500 = "#C46E00";
export const COLORS_AMBER400 = "#DF9500";
export const COLORS_AMBER300 = "#FFB749";
export const COLORS_AMBER200 = "#FFC67C";
export const COLORS_AMBER100 = "#FFE4B7";
export const COLORS_AMBER50 = "#FFF1E1";
export const COLORS_ORANGE900 = "#461A00";
export const COLORS_ORANGE800 = "#823006";
export const COLORS_ORANGE700 = "#A33B04";
export const COLORS_ORANGE600 = "#C54600";
export const COLORS_ORANGE500 = "#E65300";
export const COLORS_ORANGE400 = "#FC823A";
export const COLORS_ORANGE300 = "#FFB48C";
export const COLORS_ORANGE200 = "#FFD3BC";
export const COLORS_ORANGE100 = "#FEE2D4";
export const COLORS_ORANGE50 = "#FFF0E9";
export const COLORS_RED900 = "#520810";
export const COLORS_RED800 = "#950F22";
export const COLORS_RED700 = "#BB032A";
export const COLORS_RED600 = "#DE1135";
export const COLORS_RED500 = "#F83446";
export const COLORS_RED400 = "#FC7F79";
export const COLORS_RED300 = "#FFB2AB";
export const COLORS_RED200 = "#FFD2CD";
export const COLORS_RED100 = "#FFE1DE";
export const COLORS_RED50 = "#FFF0EE";
export const COLORS_BLACK = "#000000";
export const COLORS_GRAY950 = "#0D0D0D";
export const COLORS_GRAY900 = "#282828";
export const COLORS_GRAY800 = "#4B4B4B";
export const COLORS_GRAY700 = "#5E5E5E";
export const COLORS_GRAY600 = "#727272";
export const COLORS_GRAY500 = "#868686";
export const COLORS_GRAY400 = "#A6A6A6";
export const COLORS_GRAY300 = "#BBBBBB";
export const COLORS_GRAY200 = "#DDDDDD";
export const COLORS_GRAY100 = "#E8E8E8";
export const COLORS_GRAY50 = "#F3F3F3";
export const COLORS_COOL_GRAY900 = "#141519";
export const COLORS_COOL_GRAY800 = "#202229";
export const COLORS_COOL_GRAY700 = "#2C2F3A";
export const COLORS_COOL_GRAY600 = "#464D60";
export const COLORS_COOL_GRAY500 = "#636B7F";
export const COLORS_COOL_GRAY400 = "#A1A9BA";
export const COLORS_COOL_GRAY300 = "#D4D9E2";
export const COLORS_COOL_GRAY200 = "#EAEDF3";
export const COLORS_COOL_GRAY100 = "#F3F5F9";
export const COLORS_COOL_GRAY50 = "#F9F9FC";
export const COLORS_WHITE = "#FFFFFF";
export const COLORS_DARK_OPACITY_100 = "rgba(0, 0, 0, 0.08)";
export const COLORS_DARK_OPACITY_200 = "rgba(0, 0, 0, 0.12)";
export const COLORS_DARK_OPACITY_300 = "rgba(0, 0, 0, 0.16)";
export const COLORS_DARK_OPACITY_400 = "rgba(0, 0, 0, 0.2)";
export const COLORS_DARK_OPACITY_500 = "rgba(0, 0, 0, 0.24)";
export const COLORS_DARK_OPACITY_600 = "rgba(0, 0, 0, 0.32)";
export const COLORS_LIGHT_OPACITY_100 = "rgba(255, 255, 255, 0.08)";
export const COLORS_LIGHT_OPACITY_200 = "rgba(255, 255, 255, 0.12)";
export const COLORS_LIGHT_OPACITY_300 = "rgba(255, 255, 255, 0.16)";
export const COLORS_LIGHT_OPACITY_400 = "rgba(255, 255, 255, 0.2)";
export const COLORS_LIGHT_OPACITY_500 = "rgba(255, 255, 255, 0.24)";
export const COLORS_LIGHT_OPACITY_600 = "rgba(255, 255, 255, 0.32)";
export const CORE_WHITE = "#FFFFFF";
export const CORE_BLACK = "#000000";
export const BACKGROUND_SCREEN = "#F3F5F9";
export const BACKGROUND_ELEVATED = "#FFFFFF";
export const BACKGROUND_OVERLAY = "rgba(0, 0, 0, 0.3)";
export const SURFACE_PRIMARY = "#FFFFFF";
export const SURFACE_SECONDARY = "#F9F9FC";
export const SURFACE_TERTIARY = "#F3F5F9";
export const SURFACE_ACCENT = "#EFF4FE";
export const SURFACE_DISABLED = "#EAEDF3";
export const ACTION_PRIMARY = "#0D0D0D";
export const ACTION_PRIMARY_INVERSE = "#F9F9FC";
export const ACTION_SECONDARY = "#636B7F";
export const ACTION_DISABLED = "#D4D9E2";
export const ACTION_DISTRUCTIVE = "#DE1135";
export const ACTION_ACCENT = "#266EF1";
export const CONTENT_PRIMARY = "#141519";
export const CONTENT_SECONDARY = "#636B7F";
export const CONTENT_DISABLED = "#A1A9BA";
export const CONTENT_PRIMARY_INVERSE = "#F9F9FC";
export const CONTENT_ACCENT = "#1153C0";
export const BORDER_DIVIDER = "#D4D9E2";
export const BORDER_OUTLINE = "#A1A9BA";
export const BORDER_ACTION = "#1153C0";
export const STATE_HOVERED_PRIMARY = "rgba(255, 255, 255, 0.2)";
export const STATE_HOVERED_SECONDARY = "#F9F9FC";
export const STATE_SELECTED = "#F3F5F9";
export const STATE_PRESSED_PRIMARY = "rgba(255, 255, 255, 0.32)";
export const STATE_PRESSED_SECONDARY = "#F3F5F9";
export const STATE_FOCUS_RING = "#068BEE";
export const STATE_FOCUS_OFFSET = "#FFFFFF";
export const SENTIMENT_POSITIVE_BACKGROUND_STRONG = "#009A51";
export const SENTIMENT_POSITIVE_BACKGROUND_LIGHT = "#D3EFDA";
export const SENTIMENT_POSITIVE_FOREGROUND = "#166C3B";
export const SENTIMENT_POSITIVE_BORDER = "#009A51";
export const SENTIMENT_WARNING_BACKGROUND_STRONG = "#FC823A";
export const SENTIMENT_WARNING_BACKGROUND_LIGHT = "#FEE2D4";
export const SENTIMENT_WARNING_FOREGROUND = "#C54600";
export const SENTIMENT_WARNING_BORDER = "#FC823A";
export const SENTIMENT_NEGATIVE_BACKGROUND_STRONG = "#F83446";
export const SENTIMENT_NEGATIVE_BACKGROUND_LIGHT = "#FFE1DE";
export const SENTIMENT_NEGATIVE_FOREGROUND = "#DE1135";
export const SENTIMENT_NEGATIVE_BORDER = "#F83446";
export const SENTIMENT_NEUTRAL_BACKGROUND_STRONG = "#636B7F";
export const SENTIMENT_NEUTRAL_BACKGROUND_LIGHT = "#EAEDF3";
export const SENTIMENT_NEUTRAL_FOREGROUND = "#464D60";
export const SENTIMENT_NEUTRAL_BORDER = "#A1A9BA";
export const SHADOW_SHADOW_SOFT = "rgba(0, 0, 0, 0.08)";
export const SHADOW_SHADOW_STRONG = "rgba(0, 0, 0, 0.16)";
export const SHADOW_SHADOW_MEDIUM = "rgba(0, 0, 0, 0.12)";
export const EXRPESSION_BLUE_BLUE_BACKGROUND_STRONG = "#266EF1";
export const EXRPESSION_BLUE_BLUE_BACKGROUND_LIGHT = "#DEE9FE";
export const EXRPESSION_BLUE_BLUE_FOREGROUND = "#1153C0";
export const EXRPESSION_MAGENTA_MAGENTA_BACKGROUND_STRONG = "#CA26A5";
export const EXRPESSION_MAGENTA_MAGENTA_BACKGROUND_LIGHT = "#FEDFF3";
export const EXRPESSION_MAGENTA_MAGENTA_FOREGROUND = "#A91A90";
export const EXRPESSION_TEAL_TEAL_BACKGROUND_STRONG = "#007F8C";
export const EXRPESSION_TEAL_TEAL_BACKGROUND_LIGHT = "#CDEEF3";
export const EXRPESSION_TEAL_TEAL_FOREGROUND = "#016974";
export const EXRPESSION_PURPLE_PURPLE_BACKGROUND_STRONG = "#944DE7";
export const EXRPESSION_PURPLE_PURPLE_BACKGROUND_LIGHT = "#F2E3FF";
export const EXRPESSION_PURPLE_PURPLE_FOREGROUND = "#7C3EC3";
export const EXRPESSION_LIME_LIME_BACKGROUND_STRONG = "#4F7F06";
export const EXRPESSION_LIME_LIME_BACKGROUND_LIGHT = "#DEEEC6";
export const EXRPESSION_LIME_LIME_FOREGROUND = "#3F6900";
export const BRAND_BRAND_PRIMARY = "#AACB42";
export const BRAND_BRAND_SECONDARY = "#7A7A7C";
export const TYPOGRAPHY_WEIGHT_DISPLAY = "700px";
export const TYPOGRAPHY_WEIGHT_HEADING = "700px";
export const TYPOGRAPHY_WEIGHT_LABEL = "600px";
export const TYPOGRAPHY_WEIGHT_PARAGRAPH = "400px";
export const TYPOGRAPHY_SIZE_DISPLAY_LARGE = "96px";
export const TYPOGRAPHY_SIZE_DISPLAY_MEDIUM = "64px";
export const TYPOGRAPHY_SIZE_DISPLAY_SMALL = "48px";
export const TYPOGRAPHY_SIZE_HEADING_XXLARGE = "40px";
export const TYPOGRAPHY_SIZE_HEADING_XLARGE = "36px";
export const TYPOGRAPHY_SIZE_HEADING_LARGE = "32px";
export const TYPOGRAPHY_SIZE_HEADING_MEDIUM = "28px";
export const TYPOGRAPHY_SIZE_HEADING_SMALL = "24px";
export const TYPOGRAPHY_SIZE_HEADING_XSMALL = "20px";
export const TYPOGRAPHY_SIZE_LABEL_LARGE = "18px";
export const TYPOGRAPHY_SIZE_LABEL_MEDIUM = "16px";
export const TYPOGRAPHY_SIZE_LABEL_SMALL = "14px";
export const TYPOGRAPHY_SIZE_LABEL_XSMALL = "12px";
export const TYPOGRAPHY_SIZE_PARAGRAPH_LARGE = "18px";
export const TYPOGRAPHY_SIZE_PARAGRAPH_MEDIUM = "16px";
export const TYPOGRAPHY_SIZE_PARAGRAPH_SMALL = "14px";
export const TYPOGRAPHY_SIZE_PARAGRAPH_XSMALL = "12px";
export const TYPOGRAPHY_LINE_HEIGHT_DISPLAY_LARGE = "112px";
export const TYPOGRAPHY_LINE_HEIGHT_DISPLAY_MEDIUM = "72px";
export const TYPOGRAPHY_LINE_HEIGHT_DISPLAY_SMALL = "56px";
export const TYPOGRAPHY_LINE_HEIGHT_HEADING_XXLARGE = "52px";
export const TYPOGRAPHY_LINE_HEIGHT_HEADING_XLARGE = "44px";
export const TYPOGRAPHY_LINE_HEIGHT_HEADING_LARGE = "40px";
export const TYPOGRAPHY_LINE_HEIGHT_HEADING_MEDIUM = "36px";
export const TYPOGRAPHY_LINE_HEIGHT_HEADING_SMALL = "32px";
export const TYPOGRAPHY_LINE_HEIGHT_HEADING_XSMALL = "28px";
export const TYPOGRAPHY_LINE_HEIGHT_LABEL_LARGE = "24px";
export const TYPOGRAPHY_LINE_HEIGHT_LABEL_MEDIUM = "24px";
export const TYPOGRAPHY_LINE_HEIGHT_LABEL_SMALL = "20px";
export const TYPOGRAPHY_LINE_HEIGHT_LABEL_XSMALL = "16px";
export const TYPOGRAPHY_LINE_HEIGHT_PARAGRAPH_LARGE = "24px";
export const TYPOGRAPHY_LINE_HEIGHT_PARAGRAPH_MEDIUM = "24px";
export const TYPOGRAPHY_LINE_HEIGHT_PARAGRAPH_SMALL = "20px";
export const TYPOGRAPHY_LINE_HEIGHT_PARAGRAPH_XSMALL = "16px";
export const INSET_COMPONENT_INSET_COMPONENT_SM_X = "12px"; // Horizontal (left/right) padding of small interactive controls — compact buttons, small inputs in dense tables. Always larger than inset-component-sm-y for optical balance. | ai-group:density | ai-impact:medium | ai-constraint:must be > inset-component-sm-y
export const INSET_COMPONENT_INSET_COMPONENT_SM_Y = "8px"; // Vertical (top/bottom) padding of small interactive controls. Ratio ~0.67 of inset-component-sm-x. Directly controls tap target height. | ai-group:density | ai-impact:medium | ai-constraint:must be < inset-component-sm-x
export const INSET_COMPONENT_INSET_COMPONENT_MD_X = "16px"; // Horizontal padding of default/medium interactive controls — standard buttons and inputs. Most-used inset token. Increasing makes controls feel more generous and spacious. | ai-group:density | ai-impact:high | ai-constraint:must be > inset-component-md-y
export const INSET_COMPONENT_INSET_COMPONENT_MD_Y = "12px"; // Vertical padding of medium interactive controls. Directly determines tap target height. Ratio ~0.75 of inset-component-md-x. Never set equal to or greater than x. | ai-group:density | ai-impact:high | ai-constraint:must be < inset-component-md-x, ratio ~0.75
export const INSET_COMPONENT_INSET_COMPONENT_LG_X = "24px"; // Horizontal padding of large interactive controls — prominent CTAs, hero inputs, full-width actions. | ai-group:density | ai-impact:medium | ai-constraint:must be > inset-component-lg-y
export const INSET_COMPONENT_INSET_COMPONENT_LG_Y = "16px"; // Vertical padding of large interactive controls. Ratio ~0.67 of inset-component-lg-x. | ai-group:density | ai-impact:medium | ai-constraint:must be < inset-component-lg-x
export const INSET_INLINE_INSET_INLINE_SM_X = "8px"; // Horizontal padding of small inline elements — notification counts, dot badges, tiny status indicators. Always larger than inset-inline-sm-y. | ai-group:density | ai-impact:low
export const INSET_INLINE_INSET_INLINE_SM_Y = "4px"; // Vertical padding of small inline elements. Extremely tight — element sits flush with surrounding text line. | ai-group:density | ai-impact:low | ai-constraint:max 4px
export const INSET_INLINE_INSET_INLINE_MD_X = "12px"; // Horizontal padding of default chips, badges, filter tags. Standard pill padding. | ai-group:density | ai-impact:medium
export const INSET_INLINE_INSET_INLINE_MD_Y = "4px"; // Vertical padding of default chips and badges. Never exceed 8px or badges break text line rhythm. | ai-group:density | ai-impact:medium | ai-constraint:max 8px
export const INSET_INLINE_INSET_INLINE_LG_X = "16px"; // Horizontal padding of large filter chips and prominent category tags. | ai-group:density | ai-impact:low
export const INSET_INLINE_INSET_INLINE_LG_Y = "8px"; // Vertical padding of large chips and tags. | ai-group:density | ai-impact:low | ai-constraint:max 8px
export const INSET_CONTAINER_INSET_CONTAINER_SM = "12px"; // Compact container padding — dense lists, compact cards, tight info boxes. Equal on all sides — do not split x/y for containers. | ai-group:density | ai-impact:medium
export const INSET_CONTAINER_INSET_CONTAINER_MD = "16px"; // Default card and panel padding. The most common container inset. Equal on all sides. | ai-group:density | ai-impact:high
export const INSET_CONTAINER_INSET_CONTAINER_LG = "24px"; // Comfortable padding for modals, bottom sheets, prominent panels. Equal on all sides. | ai-group:density | ai-impact:high
export const INSET_CONTAINER_INSET_CONTAINER_XL = "32px"; // Generous padding for hero cards, onboarding panels, full-page sections. Equal on all sides. | ai-group:density | ai-impact:medium
export const INSET_SECTION_INSET_SECTION_SM = "24px"; // Compact page section padding — mobile default and dense content pages. Controls macro breathing room of the full page layout. | ai-group:density | ai-impact:high
export const INSET_SECTION_INSET_SECTION_MD = "48px"; // Standard page section padding — tablet and desktop default. Main lever for overall page airiness. Increasing alone makes the page feel editorial and open. | ai-group:density | ai-impact:high
export const INSET_SECTION_INSET_SECTION_LG = "0px"; // Spacious page section padding — hero sections, feature showcases, marketing pages. | ai-group:density | ai-impact:high
export const GAP_GAP_ITEMS_TIGHT = "8px"; // Gap between closely grouped controls — button groups, radio clusters, segmented controls. Decreasing fuses elements together; increasing separates them into individual items. | ai-group:density | ai-impact:medium
export const GAP_GAP_ITEMS_DEFAULT = "12px"; // Standard gap between sibling UI elements — form field rows, list items, menu options. The most-used gap token. Changing this has broad impact on perceived density across the entire UI. | ai-group:density | ai-impact:high
export const GAP_GAP_ITEMS_COMFORTABLE = "16px"; // Gap for grid items and navigation — card grid cells, nav rail items. Larger than default to give breathing room between cards. | ai-group:density | ai-impact:medium
export const GAP_GAP_STACK_TIGHT = "8px"; // Vertical gap between visually grouped text elements — heading + subheading, stat value + label. Controls whether these pairs read as a single unit. Never exceed 12px or the grouping breaks. | ai-group:density | ai-impact:medium | ai-constraint:max 12px to preserve visual grouping
export const GAP_GAP_STACK_DEFAULT = "16px"; // Vertical gap between distinct but related content groups — between a form group and the next, between a heading and body text. The primary lever for vertical page rhythm. | ai-group:density | ai-impact:high
export const GAP_GAP_STACK_LOOSE = "24px"; // Vertical gap between loosely related content areas — rows of cards, sidebar sections. Creates visual separation without the weight of a full section break. | ai-group:density | ai-impact:medium
export const GAP_GAP_STACK_SECTION = "64px"; // Vertical gap between major page sections. Largest gap token in the system. Reducing makes the page feel like a continuous scroll; increasing creates distinct visual chapters. | ai-group:density | ai-impact:high
export const GAP_GAP_INLINE_TIGHT = "8px"; // Horizontal gap between tightly packed inline elements — stacked avatars, inline chip groups, tag clouds. | ai-group:density | ai-impact:low
export const GAP_GAP_INLINE_DEFAULT = "12px"; // Standard horizontal gap — toolbar actions, breadcrumb segments, nav items. Increasing makes navigation feel more open and touch-friendly. | ai-group:density | ai-impact:medium
export const GAP_GAP_INLINE_LOOSE = "16px"; // Generous horizontal gap for top-level navigation and primary tab bars. Larger gaps signal these are the primary navigational choices. | ai-group:density | ai-impact:medium
export const GAP_GAP_RELATED_TIGHT = "8px";
export const GAP_GAP_RELATED_DEFAULT = "16px";
export const LAYOUT_LAYOUT_PAGE_MARGIN = "40px"; // Distance from the viewport edge to the content area. Controls how close content sits to the screen edge. Scales up on larger breakpoints — 16px mobile, 24px tablet, 40px desktop. | ai-group:density | ai-impact:high
export const LAYOUT_LAYOUT_PAGE_GUTTER = "24px"; // Gap between grid columns. Mirrors the grid.gutter value. Scales up on larger breakpoints — 16px mobile, 20px tablet, 24px desktop. | ai-group:density | ai-impact:medium
export const LAYOUT_LAYOUT_CONTENT_GAP = "32px"; // Gap between major content regions — main content area and sidebar. Responsive. | ai-group:density | ai-impact:medium
export const LAYOUT_LAYOUT_CONTENT_GAP_LARGE = "64px"; // Large content region gap for wide two-column layouts on desktop. | ai-group:density | ai-impact:medium
export const CORNER_RADIUS_CORNER_NONE = "0px"; // No rounding — full-bleed elements, edge-to-edge banners, explicitly sharp components. | ai-group:roundness
export const CORNER_RADIUS_CORNER_XSMALL = "2px"; // Barely rounded — for very subtle softening, almost-sharp aesthetic. | ai-group:roundness
export const CORNER_RADIUS_CORNER_SMALL = "4px"; // Slight rounding — default for interactive controls (buttons, inputs) in the default personality. | ai-group:roundness
export const CORNER_RADIUS_CORNER_MEDIUM = "8px"; // Moderate rounding — default for cards and container surfaces. | ai-group:roundness
export const CORNER_RADIUS_CORNER_LARGE = "12px"; // Prominent rounding — modals, popovers, overlays in default personality. | ai-group:roundness
export const CORNER_RADIUS_CORNER_XLARGE = "16px"; // Strong rounding — interactive controls in rounded personality, container surfaces in bubbly. | ai-group:roundness
export const CORNER_RADIUS_CORNER_2XLARGE = "24px"; // Very strong rounding — used in bubbly/expressive personality modes. | ai-group:roundness
export const CORNER_RADIUS_CORNER_FULL = "999px"; // Fully circular/pill — chips, badges, avatar images, toggle switches. | ai-group:roundness
export const STROKE_STROKE_HAIRLINE = "0.5px"; // Hairline border — structural dividers between list rows, table cells. Barely perceptible by design. | ai-group:weight
export const STROKE_STROKE_THIN = "1px"; // Standard border width — interactive form elements at rest: inputs, selects, card outlines. Universal default. | ai-group:weight
export const STROKE_STROKE_MEDIUM = "1.5px"; // Medium border — slightly more prominent outlines, active states where extra visibility is needed. | ai-group:weight
export const STROKE_STROKE_BOLD = "2px"; // Bold border — focus rings, active input borders, strong emphasis outlines. | ai-group:weight
export const RADIUS_RADIUS_INTERACTIVE = "4px"; // Corner radius of all interactive controls — buttons, inputs, selects, dropdowns. The single biggest lever for roundness personality. Changing this shifts product character from sharp/corporate to soft/modern. | ai-group:roundness | ai-impact:high | ai-constraint:must be <= radius.container
export const RADIUS_RADIUS_CONTAINER = "8px"; // Corner radius of card-like containers — cards, panels, info boxes. Should always be >= radius.interactive to maintain visual harmony. | ai-group:roundness | ai-impact:high | ai-constraint:must be >= radius.interactive
export const RADIUS_RADIUS_OVERLAY = "12px"; // Corner radius of floating surfaces — modals, bottom sheets, popovers, tooltips. Larger radius signals softness and approachability. | ai-group:roundness | ai-impact:medium
export const RADIUS_RADIUS_TAG = "999px"; // Corner radius of chips, badges, tags — fully rounded pill shape by default. Reducing creates rectangular labels. Only change if brand calls for square badges. | ai-group:roundness | ai-impact:medium
export const RADIUS_RADIUS_AVATAR = "999px"; // Corner radius for user avatars and profile images — circular by default. Avoid changing unless brand explicitly calls for square avatars. | ai-group:roundness | ai-impact:low
export const RADIUS_RADIUS_IMAGE = "4px"; // Corner radius for media thumbnails and content images. Matches radius.interactive by default. | ai-group:roundness | ai-impact:low
export const RADIUS_RADIUS_NONE = "0px"; // Explicitly no rounding — for full-bleed elements that should never have rounded corners regardless of personality mode. | ai-group:locked | ai-locked:true
export const FOCUS_FOCUS_RING_WIDTH = "2px"; // Width of outer accessibility focus ring. Minimum 2px per WCAG 2.4.11. Never reduce below 2px. | ai-group:locked | ai-locked:true | ai-constraint:minimum 2px WCAG requirement
export const FOCUS_FOCUS_RING_OFFSET = "2px"; // Gap between focused element edge and focus ring. 2px creates clear visual separation. | ai-group:locked | ai-locked:true
export const GRID_MARGIN = "40px";
export const GRID_GUTTER = "24px";
export const GRID_COLUMNS = "12px";
export const WORKSPACE_WIDTH = "1440px";
export const WORKSPACE_MIN_WIDTH = "1024px";
export const WORKSPACE_MAX_WIDTH = "1920px";
export const CANVAS_MAX_WIDTH = "1976px";
export const CANVAS_MIN_WIDTH = "1080px";
export const SHOW_SIDEBAR = "1px";
export const SHADOW_SMALL_SHADOW_SMALL_BLUR_1 = "3px";
export const SHADOW_SMALL_SHADOW_SMALL_BLUR_2 = "6px";
export const SHADOW_SMALL_SHADOW_SMALL_Y_1 = "1px";
export const SHADOW_SMALL_SHADOW_SMALL_Y_2 = "3px";
export const SHADOW_MEDIUM_SHADOW_MEDIUM_BLUR_1 = "8px";
export const SHADOW_MEDIUM_SHADOW_MEDIUM_BLUR_2 = "10px";
export const SHADOW_MEDIUM_SHADOW_MEDIUM_Y_1 = "1px";
export const SHADOW_MEDIUM_SHADOW_Y_L2_2 = "4px";
export const SHADOW_LARGE_SHADOW_LARGE_BLUR_2 = "24px";
export const SHADOW_LARGE_SHADOW_LARGE_BLUR_1 = "16px";
export const SHADOW_LARGE_SHADOW_LARGE_Y_1 = "2px";
export const SHADOW_LARGE_SHADOW_LARGE_Y_2 = "16px";
