#!/usr/bin/env node
/**
 * tokens/build.js
 *
 * Converts tokens/figma/**\/*.json → src/tokens.generated.css
 *
 * Usage:  node tokens/build.js
 * or:     npm run tokens:build
 */

import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT     = join(__dirname, '..')
const FIGMA    = join(__dirname, 'figma')

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Spaces and special chars → single dash (preserves existing dashes) */
function toKebab(str) {
  return str.trim().replace(/\s+/g, '-')
}

/**
 * Recursively flatten a W3C DTCG token tree into [[cssVarName, tokenNode], …]
 * Skips $-prefixed metadata keys and the -internal group Figma injects.
 */
function flatten(obj, prefix, out = []) {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$') || key === '-internal') continue
    const segment = toKebab(key)
    const fullKey = prefix ? `${prefix}-${segment}` : segment
    if (val.$type) {
      out.push([fullKey, val])
    } else if (val && typeof val === 'object') {
      flatten(val, fullKey, out)
    }
  }
  return out
}

/** sRGB component (0–1) → 0–255 integer */
function ch(v) { return Math.round(v * 255) }

/**
 * Convert a token node to its CSS value string.
 * Returns null for tokens we can't/shouldn't output.
 */
function tokenValue(key, token) {
  const { $type, $value, $extensions } = token
  const scopes = $extensions?.['com.figma.scopes'] ?? []

  if ($type === 'color') {
    const { components: [r, g, b], alpha, hex } = $value
    // Preserve alpha for semi-transparent tokens (overlay, state, shadow)
    if (typeof alpha === 'number' && alpha < 0.999) {
      const a = +alpha.toFixed(3).replace(/0+$/, '').replace(/\.$/, '')
      return `rgba(${ch(r)}, ${ch(g)}, ${ch(b)}, ${a})`
    }
    return hex
  }

  if ($type === 'number') {
    // font-weight must be unitless; grid-columns is a count, not a length
    const unitless = scopes.includes('FONT_STYLE') || key === 'grid-columns'
    return unitless ? String($value) : `${$value}px`
  }

  if ($type === 'string' || $type === 'fontFamily') {
    // Font-family strings get a generic sans-serif fallback appended
    const isFontFamily = key.includes('font-family')
    return isFontFamily ? `'${$value}', sans-serif` : $value
  }

  return null
}

/** Render an array of [key, token] pairs as indented CSS custom properties */
function renderProps(pairs, indent = '  ') {
  return pairs
    .map(([key, token]) => {
      const val = tokenValue(key, token)
      return val !== null ? `${indent}--${key}: ${val};` : null
    })
    .filter(Boolean)
    .join('\n')
}

// ── Load helpers ──────────────────────────────────────────────────────────────

function load(relPath) {
  return JSON.parse(readFileSync(join(FIGMA, relPath), 'utf8'))
}

/** Load a JSON file and flatten, optionally injecting a leading prefix segment */
function loadTokens(relPath, prefix = '') {
  return flatten(load(relPath), prefix || undefined)
}

// ── Assemble token sets ───────────────────────────────────────────────────────

//  :root — light mode + desktop defaults
const rootTokens = [
  ...loadTokens('primitives.json'),
  ...loadTokens('colors/light.json'),
  ...loadTokens('elevation/light.json'),
  ...loadTokens('shapes/shapes.json'),
  ...loadTokens('spacing/desktop.json'),
  ...loadTokens('grid/desktop.json'),
  // typography/* keys (weight, size, line height) get a 'typography' prefix so
  // they stay consistent with component code: --typography-weight-paragraph etc.
  ...loadTokens('typography/desktop.json', 'typography'),
]

// [data-theme="dark"] — only the tokens that differ in dark mode
const darkTokens = [
  ...loadTokens('colors/dark.json'),
  ...loadTokens('elevation/dark.json'),
]

// Tablet breakpoint — spacing + grid differ; typography tablet = desktop so skip
const tabletTokens = [
  ...loadTokens('spacing/tablet.json'),
  ...loadTokens('grid/tablet.json'),
]

// Mobile breakpoint — spacing, grid, and some typography sizes differ
const mobileTokens = [
  ...loadTokens('spacing/mobile.json'),
  ...loadTokens('grid/mobile.json'),
  ...loadTokens('typography/mobile.json', 'typography'),
]

// ── Render output ─────────────────────────────────────────────────────────────

const lines = [
  '/* AUTO-GENERATED by tokens/build.js — do not edit manually */',
  '/* To update: npm run tokens:build                           */',
  '',
  ':root {',
  renderProps(rootTokens),
  '}',
  '',
  '[data-theme="dark"], .dark {',
  renderProps(darkTokens),
  '}',
]

if (tabletTokens.length) {
  lines.push(
    '',
    '@media (max-width: 1024px) {',
    '  :root {',
    renderProps(tabletTokens, '    '),
    '  }',
    '}',
  )
}

if (mobileTokens.length) {
  lines.push(
    '',
    '@media (max-width: 768px) {',
    '  :root {',
    renderProps(mobileTokens, '    '),
    '  }',
    '}',
  )
}

lines.push('')

// ── Write ─────────────────────────────────────────────────────────────────────

const outPath = join(ROOT, 'src/tokens.generated.css')
writeFileSync(outPath, lines.join('\n'), 'utf8')

const count = rootTokens.length + darkTokens.length + tabletTokens.length + mobileTokens.length
console.log(`✓ ${count} tokens → ${outPath.replace(ROOT + '/', '')}`)
