#!/usr/bin/env node
/**
 * tokens/build.js
 *
 * Converts tokens/figma/**\/*.json → src/tokens.generated.css
 *                                  → src/tokens.metadata.json
 *
 * Usage:  node tokens/build.js
 * or:     npm run tokens:build
 */

import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT     = join(__dirname, '..')
const FIGMA    = join(__dirname, 'figma')

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Spaces and special chars → single dash (preserves existing dashes) */
function toKebab(str) {
  return str.trim().replace(/\s+/g, '-')
}

/**
 * Recursively flatten a W3C DTCG token tree into [[cssVarName, tokenNode], …]
 * Skips $-prefixed metadata keys and the -internal group Figma injects.
 */
function flatten(obj, prefix, out = []) {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$') || key === '-internal') continue
    const segment = toKebab(key)
    const fullKey = prefix ? `${prefix}-${segment}` : segment
    if (val.$type) {
      out.push([fullKey, val])
    } else if (val && typeof val === 'object') {
      flatten(val, fullKey, out)
    }
  }
  return out
}

/** sRGB component (0–1) → 0–255 integer */
function ch(v) { return Math.round(v * 255) }

/**
 * Convert a token node to its CSS value string.
 * Returns null for tokens we can't/shouldn't output.
 */
function tokenValue(key, token) {
  const { $type, $value, $extensions } = token
  const scopes = $extensions?.['com.figma.scopes'] ?? []

  if ($type === 'color') {
    const { components: [r, g, b], alpha, hex } = $value
    // Preserve alpha for semi-transparent tokens (overlay, state, shadow)
    if (typeof alpha === 'number' && alpha < 0.999) {
      const a = +alpha.toFixed(3).replace(/0+$/, '').replace(/\.$/, '')
      return `rgba(${ch(r)}, ${ch(g)}, ${ch(b)}, ${a})`
    }
    return hex
  }

  if ($type === 'number') {
    // Unitless: font-weight, column counts, boolean flags
    const unitless = scopes.includes('FONT_STYLE')
      || key === 'layout-grid-columns'   // was grid-columns
      || key === 'layout-show-sidebar'   // boolean flag in layout collection
    return unitless ? String($value) : `${$value}px`
  }

  if ($type === 'string' || $type === 'fontFamily') {
    // Font-family strings get a generic sans-serif fallback appended
    const isFontFamily = key.includes('font-family')
    return isFontFamily ? `'${$value}', sans-serif` : $value
  }

  return null
}

/** Render an array of [key, token] pairs as indented CSS custom properties */
function renderProps(pairs, indent = '  ') {
  return pairs
    .map(([key, token]) => {
      const val = tokenValue(key, token)
      return val !== null ? `${indent}--${key}: ${val};` : null
    })
    .filter(Boolean)
    .join('\n')
}

// ── Load helpers ──────────────────────────────────────────────────────────────

function load(relPath) {
  return JSON.parse(readFileSync(join(FIGMA, relPath), 'utf8'))
}

/** Load a JSON file and flatten, optionally injecting a leading prefix segment */
function loadTokens(relPath, prefix = '') {
  return flatten(load(relPath), prefix || undefined)
}

// ── Assemble token sets ───────────────────────────────────────────────────────

//  :root — light mode + desktop defaults
const rootTokens = [
  ...loadTokens('primitives.json'),
  ...loadTokens('colors/light.json'),
  ...loadTokens('elevation/light.json'),
  ...loadTokens('shapes/shapes.json'),
  ...loadTokens('spacing/desktop.json'),
  // layout/* was formerly grid/* — prefix 'layout' so vars are --layout-grid-*
  ...loadTokens('layout/desktop.json', 'layout'),
  // typography/* keys get a 'typography' prefix:
  // --typography-weight-paragraph, --typography-line-height-*, etc.
  ...loadTokens('typography/desktop.json', 'typography'),
]

// [data-theme="dark"] — only the tokens that differ in dark mode
const darkTokens = [
  ...loadTokens('colors/dark.json'),
  ...loadTokens('elevation/dark.json'),
]

// Tablet breakpoint — spacing + layout differ
const tabletTokens = [
  ...loadTokens('spacing/tablet.json'),
  ...loadTokens('layout/tablet.json', 'layout'),
]

// Mobile breakpoint — spacing, layout, and some typography sizes differ
const mobileTokens = [
  ...loadTokens('spacing/mobile.json'),
  ...loadTokens('layout/mobile.json', 'layout'),
  ...loadTokens('typography/mobile.json', 'typography'),
]

// ── Render CSS output ─────────────────────────────────────────────────────────

const lines = [
  '/* AUTO-GENERATED by tokens/build.js — do not edit manually */',
  '/* To update: npm run tokens:build                           */',
  '',
  ':root {',
  renderProps(rootTokens),
  '}',
  '',
  '[data-theme="dark"], .dark {',
  renderProps(darkTokens),
  '}',
]

if (tabletTokens.length) {
  lines.push(
    '',
    '@media (max-width: 1024px) {',
    '  :root {',
    renderProps(tabletTokens, '    '),
    '  }',
    '}',
  )
}

if (mobileTokens.length) {
  lines.push(
    '',
    '@media (max-width: 768px) {',
    '  :root {',
    renderProps(mobileTokens, '    '),
    '  }',
    '}',
  )
}

lines.push('')

// ── Write CSS ─────────────────────────────────────────────────────────────────

const cssPath = join(ROOT, 'src/tokens.generated.css')
writeFileSync(cssPath, lines.join('\n'), 'utf8')

const cssCount = rootTokens.length + darkTokens.length + tabletTokens.length + mobileTokens.length
console.log(`✓ ${cssCount} tokens → ${cssPath.replace(ROOT + '/', '')}`)

// ── Generate metadata ─────────────────────────────────────────────────────────
//
// For each token that has a $description, emit a JSON record:
//   {
//     "cssVar": "--foo-bar",
//     "description": "Full description text (stripped of ai-* tags)",
//     "aiGroup": "density",          // from | ai-group:xxx |
//     "aiImpact": "high",            // from | ai-impact:xxx |
//     "collection": "colors"         // source file group
//   }

const AI_GROUP_RE  = /\|\s*ai-group:(\S+?)\s*\|/
const AI_IMPACT_RE = /\|\s*ai-impact:(\S+?)\s*\|/
const AI_TAG_RE    = /\s*\|\s*ai-[^|]+\|\s*/g

/** Derive a human-readable collection name from the file path */
function collectionName(relPath) {
  return relPath.split('/')[0]  // e.g. 'colors', 'spacing', 'layout', 'typography'
}

/** All (relPath, prefix) pairs that were loaded — mirrors the loadTokens calls */
const allSources = [
  // ── :root ───────────────────────────────────────────────────
  { rel: 'primitives.json',         prefix: '',          mode: 'root'    },
  { rel: 'colors/light.json',       prefix: '',          mode: 'root'    },
  { rel: 'elevation/light.json',    prefix: '',          mode: 'root'    },
  { rel: 'shapes/shapes.json',      prefix: '',          mode: 'root'    },
  { rel: 'spacing/desktop.json',    prefix: '',          mode: 'root'    },
  { rel: 'layout/desktop.json',     prefix: 'layout',    mode: 'root'    },
  { rel: 'typography/desktop.json', prefix: 'typography',mode: 'root'    },
  // ── dark ────────────────────────────────────────────────────
  { rel: 'colors/dark.json',        prefix: '',          mode: 'dark'    },
  { rel: 'elevation/dark.json',     prefix: '',          mode: 'dark'    },
  // ── tablet ──────────────────────────────────────────────────
  { rel: 'spacing/tablet.json',     prefix: '',          mode: 'tablet'  },
  { rel: 'layout/tablet.json',      prefix: 'layout',    mode: 'tablet'  },
  // ── mobile ──────────────────────────────────────────────────
  { rel: 'spacing/mobile.json',     prefix: '',          mode: 'mobile'  },
  { rel: 'layout/mobile.json',      prefix: 'layout',    mode: 'mobile'  },
  { rel: 'typography/mobile.json',  prefix: 'typography',mode: 'mobile'  },
]

const metadata = {}

for (const { rel, prefix, mode } of allSources) {
  const tokens = loadTokens(rel, prefix)
  const col    = collectionName(rel)

  for (const [key, token] of tokens) {
    const desc = token.$description
    if (!desc) continue

    const cssVar     = `--${key}`
    const aiGroup    = (desc.match(AI_GROUP_RE)  || [])[1] ?? null
    const aiImpact   = (desc.match(AI_IMPACT_RE) || [])[1] ?? null
    const cleanDesc  = desc.replace(AI_TAG_RE, ' ').replace(/\s{2,}/g, ' ').trim()

    // Prefer root-mode entry; only add dark/tablet/mobile if not already present
    if (!metadata[cssVar] || mode === 'root') {
      metadata[cssVar] = {
        cssVar,
        description: cleanDesc,
        aiGroup,
        aiImpact,
        collection: col,
        mode,
      }
    }
  }
}

const metaPath = join(ROOT, 'src/tokens.metadata.json')
writeFileSync(metaPath, JSON.stringify(metadata, null, 2) + '\n', 'utf8')

const metaCount = Object.keys(metadata).length
console.log(`✓ ${metaCount} token descriptions → ${metaPath.replace(ROOT + '/', '')}`)
